-- Safe admin-panel support patch.
-- Run in Supabase SQL editor before deploying the current admin changes.
-- This is additive only: it does not delete, overwrite, or rewrite volunteer data.

alter table public.app_users
add column if not exists place_of_origin text;

alter table public.recordings
add column if not exists validation_score integer not null default 0;

alter table public.recordings
add column if not exists validation_weight integer not null default 1;

create table if not exists public.validations (
  id bigint generated by default as identity primary key,
  recording_id bigint not null references public.recordings(id) on delete cascade,
  validator_id text not null,
  vote integer not null check (vote in (-1, 1)),
  created_at timestamptz not null default now()
);

create unique index if not exists validations_recording_validator_uidx
on public.validations (recording_id, validator_id);

create index if not exists validations_recording_idx
on public.validations (recording_id);

create index if not exists validations_validator_idx
on public.validations (validator_id);

alter table public.validations enable row level security;
