-- Deployment setup for the current app.
-- This script is additive: it creates missing tables, indexes, buckets,
-- triggers, and policies without dropping existing tables or data.

create extension if not exists pgcrypto;
create extension if not exists citext;

create table if not exists public.app_users (
  id uuid primary key default gen_random_uuid(),
  participant_id text not null unique,
  username citext not null unique,
  role text not null default 'volunteer'
    check (role in ('volunteer', 'content_contributor', 'researcher', 'admin')),
  display_name text,
  contact_preference text,
  mobile_number text,
  dialect text,
  dialects text[] not null default '{}',
  other_dialect text,
  gender text,
  age text,
  other_language_count text,
  other_languages text[] not null default '{}',
  comfort_language text,
  place_of_birth text,
  places_lived text[] not null default '{}',
  consent_accepted boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.recordings (
  id bigint generated by default as identity primary key,
  participant_id text not null,
  dialect text,
  gender text,
  module_id text not null,
  sentence_id text not null,
  audio_path text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  participant_id text,
  module_id text,
  sentence_id text,
  sentence_number integer,
  correct_english text,
  correction text,
  audio_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  participant_id text not null unique,
  subscription_json text not null,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.notification_logs (
  id bigint generated by default as identity primary key,
  participant_id text,
  title text,
  body text,
  status text,
  error_message text,
  sent_at timestamptz not null default now()
);

create table if not exists public.admin_accounts (
  id uuid primary key default gen_random_uuid(),
  username citext not null unique,
  display_name text,
  password_hash text not null,
  active boolean not null default true,
  created_by text,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_activity_logs (
  id bigint generated by default as identity primary key,
  admin_username text not null,
  admin_is_master boolean not null default false,
  action text not null,
  target_type text,
  target_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.app_users
add column if not exists active boolean not null default true;

create index if not exists app_users_role_idx on public.app_users (role);
create index if not exists app_users_dialect_idx on public.app_users (dialect);
create index if not exists app_users_active_idx on public.app_users (active);
create index if not exists recordings_participant_idx on public.recordings (participant_id);
create index if not exists recordings_sentence_idx on public.recordings (module_id, sentence_id);
create index if not exists feedback_participant_idx on public.feedback (participant_id);
create index if not exists admin_accounts_active_idx on public.admin_accounts (active);
create index if not exists admin_activity_logs_admin_idx on public.admin_activity_logs (admin_username);
create index if not exists admin_activity_logs_created_idx on public.admin_activity_logs (created_at);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'app_users_set_updated_at'
      and tgrelid = 'public.app_users'::regclass
  ) then
    create trigger app_users_set_updated_at
    before update on public.app_users
    for each row
    execute function public.set_updated_at();
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'push_subscriptions_set_updated_at'
      and tgrelid = 'public.push_subscriptions'::regclass
  ) then
    create trigger push_subscriptions_set_updated_at
    before update on public.push_subscriptions
    for each row
    execute function public.set_updated_at();
  end if;
end;
$$;

insert into storage.buckets (id, name, public)
values
  ('audio-recordings', 'audio-recordings', false),
  ('feedback-audio', 'feedback-audio', false)
on conflict (id) do nothing;

alter table public.app_users enable row level security;
alter table public.recordings enable row level security;
alter table public.feedback enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.notification_logs enable row level security;
alter table public.admin_accounts enable row level security;
alter table public.admin_activity_logs enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'recordings'
      and policyname = 'anon can insert recordings'
  ) then
    create policy "anon can insert recordings"
    on public.recordings
    for insert
    to anon
    with check (true);
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'feedback'
      and policyname = 'anon can insert feedback'
  ) then
    create policy "anon can insert feedback"
    on public.feedback
    for insert
    to anon
    with check (true);
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'push_subscriptions'
      and policyname = 'anon can manage push subscriptions'
  ) then
    create policy "anon can manage push subscriptions"
    on public.push_subscriptions
    for all
    to anon
    using (true)
    with check (true);
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'anon can upload audio recordings'
  ) then
    create policy "anon can upload audio recordings"
    on storage.objects
    for insert
    to anon
    with check (bucket_id = 'audio-recordings');
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'anon can update audio recordings'
  ) then
    create policy "anon can update audio recordings"
    on storage.objects
    for update
    to anon
    using (bucket_id = 'audio-recordings')
    with check (bucket_id = 'audio-recordings');
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'anon can upload feedback audio'
  ) then
    create policy "anon can upload feedback audio"
    on storage.objects
    for insert
    to anon
    with check (bucket_id = 'feedback-audio');
  end if;
end;
$$;
