-- Deployment setup for the current app.
-- This script is additive: it creates missing tables, indexes, buckets,
-- triggers, and policies without dropping existing tables or data.

create extension if not exists pgcrypto;
create extension if not exists citext;

create table if not exists public.app_users (
  id uuid primary key default gen_random_uuid(),
  participant_id text not null unique,
  username citext not null unique,
  role text not null default 'volunteer'
    check (role in ('volunteer', 'content_contributor', 'researcher', 'admin')),
  display_name text,
  contact_preference text,
  email text,
  mobile_number text,
  dialect text,
  dialects text[] not null default '{}',
  other_dialect text,
  gender text,
  age text,
  other_language_count text,
  other_languages text[] not null default '{}',
  comfort_language text,
  place_of_origin text,
  place_of_birth text,
  places_lived text[] not null default '{}',
  consent_accepted boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.recordings (
  id bigint generated by default as identity primary key,
  participant_id text not null,
  dialect text,
  gender text,
  module_id text not null,
  sentence_id text not null,
  audio_path text not null,
  transcript text,
  english_translation text,
  correction_flag boolean not null default false,
  suggested_correction text,
  validation_score integer not null default 0,
  validation_weight integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.validations (
  id bigint generated by default as identity primary key,
  recording_id bigint not null references public.recordings(id) on delete cascade,
  validator_id text not null,
  vote integer not null check (vote in (-1, 1)),
  created_at timestamptz not null default now(),
  unique (recording_id, validator_id)
);

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  participant_id text,
  module_id text,
  sentence_id text,
  sentence_number integer,
  correct_english text,
  correction text,
  audio_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  participant_id text not null unique,
  subscription_json text not null,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.notification_logs (
  id bigint generated by default as identity primary key,
  participant_id text,
  title text,
  body text,
  status text,
  error_message text,
  sent_at timestamptz not null default now()
);

create table if not exists public.admin_accounts (
  id uuid primary key default gen_random_uuid(),
  username citext not null unique,
  display_name text,
  password_hash text not null,
  active boolean not null default true,
  created_by text,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_activity_logs (
  id bigint generated by default as identity primary key,
  admin_username text not null,
  admin_is_master boolean not null default false,
  action text not null,
  target_type text,
  target_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.prompt_bank (
  id uuid primary key default gen_random_uuid(),
  prompt_id text not null,
  module_id text not null default 'general-prompts',
  module_title text not null default 'General Prompts',
  prompt_type text not null default 'translation'
    check (prompt_type in ('translation', 'elicitation', 'picture_description', 'validation', 'gamified')),
  dialect text,
  english text not null,
  transliteration text,
  media_url text,
  media_type text not null default 'none'
    check (media_type in ('none', 'image', 'audio')),
  difficulty text not null default 'short'
    check (difficulty in ('short', 'medium', 'long')),
  curriculum_stage text,
  grammatical_category text,
  weight integer not null default 1 check (weight >= 0),
  active boolean not null default true,
  sort_order integer not null default 0,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.prompt_correction_reviews (
  id uuid primary key default gen_random_uuid(),
  prompt_bank_id uuid references public.prompt_bank(id) on delete set null,
  module_id text not null,
  prompt_id text not null,
  previous_english text,
  accepted_correction text not null,
  candidate_corrections jsonb not null default '[]'::jsonb,
  accepted_feedback_id bigint references public.feedback(id) on delete set null,
  reviewed_by text,
  created_at timestamptz not null default now()
);

do $$
begin
  alter table public.prompt_bank drop constraint if exists prompt_bank_prompt_id_key;
end;
$$;

create table if not exists public.research_tasks (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  task_type text not null default 'transcription'
    check (task_type in ('transcription', 'translation', 'validation', 'metadata_review')),
  assigned_to uuid references public.app_users(id) on delete set null,
  recording_id bigint references public.recordings(id) on delete set null,
  requested_outputs text[] not null default '{}',
  source_type text not null default 'audio'
    check (source_type in ('audio', 'text', 'content_url', 'recording', 'feedback')),
  source_ref text,
  source_text text,
  instructions text,
  status text not null default 'todo'
    check (status in ('todo', 'in_progress', 'review', 'done', 'blocked')),
  priority text not null default 'normal'
    check (priority in ('low', 'normal', 'high', 'urgent')),
  due_date date,
  transcript text,
  translation text,
  researcher_notes text,
  admin_feedback text,
  notes text,
  submitted_at timestamptz,
  completed_at timestamptz,
  applied_to_recording_at timestamptz,
  applied_by text,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contributions (
  id uuid default gen_random_uuid() primary key,
  username text not null,
  role text not null,
  content_type text not null,
  media_url text,
  description text,
  language_notes text,
  speaker_metadata text,
  turn_taking_notes text,
  status text default 'pending',
  created_at timestamp default now()
);

alter table public.app_users
add column if not exists active boolean not null default true;

alter table public.app_users
add column if not exists email text;

alter table public.app_users
add column if not exists place_of_origin text;

alter table public.app_users
add column if not exists education_level text;

alter table public.app_users
add column if not exists occupation text;

alter table public.prompt_bank
add column if not exists media_type text not null default 'none';

alter table public.recordings
add column if not exists transcript text;

alter table public.recordings
add column if not exists english_translation text;

alter table public.recordings
add column if not exists correction_flag boolean not null default false;

alter table public.recordings
add column if not exists suggested_correction text;

alter table public.recordings
add column if not exists validation_score integer not null default 0;

alter table public.recordings
add column if not exists validation_weight integer not null default 1;

alter table public.research_tasks
add column if not exists recording_id bigint references public.recordings(id) on delete set null;

alter table public.research_tasks
add column if not exists requested_outputs text[] not null default '{}';

alter table public.research_tasks
add column if not exists researcher_notes text;

alter table public.research_tasks
add column if not exists admin_feedback text;

alter table public.research_tasks
add column if not exists submitted_at timestamptz;

alter table public.research_tasks
add column if not exists completed_at timestamptz;

alter table public.research_tasks
add column if not exists applied_to_recording_at timestamptz;

alter table public.research_tasks
add column if not exists applied_by text;

do $$
begin
  alter table public.prompt_bank drop constraint if exists prompt_bank_prompt_type_check;
  alter table public.prompt_bank
  add constraint prompt_bank_prompt_type_check
  check (prompt_type in ('translation', 'elicitation', 'picture_description', 'validation', 'gamified'));
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'prompt_bank_media_type_check'
      and conrelid = 'public.prompt_bank'::regclass
  ) then
    alter table public.prompt_bank
    add constraint prompt_bank_media_type_check
    check (media_type in ('none', 'image', 'audio'));
  end if;
end;
$$;

create index if not exists app_users_role_idx on public.app_users (role);
create index if not exists app_users_dialect_idx on public.app_users (dialect);
create index if not exists app_users_active_idx on public.app_users (active);
create index if not exists recordings_participant_idx on public.recordings (participant_id);
create index if not exists recordings_sentence_idx on public.recordings (module_id, sentence_id);
create unique index if not exists recordings_one_per_prompt_uidx
on public.recordings (participant_id, module_id, sentence_id);
create index if not exists validations_recording_idx on public.validations (recording_id);
create index if not exists validations_validator_idx on public.validations (validator_id);
create index if not exists feedback_participant_idx on public.feedback (participant_id);
create index if not exists admin_accounts_active_idx on public.admin_accounts (active);
create index if not exists admin_activity_logs_admin_idx on public.admin_activity_logs (admin_username);
create index if not exists admin_activity_logs_created_idx on public.admin_activity_logs (created_at);
create index if not exists prompt_bank_active_idx on public.prompt_bank (active);
create index if not exists prompt_bank_dialect_idx on public.prompt_bank (dialect);
create index if not exists prompt_bank_module_idx on public.prompt_bank (module_id);
create index if not exists prompt_bank_type_idx on public.prompt_bank (prompt_type);
create unique index if not exists prompt_bank_prompt_dialect_uidx
on public.prompt_bank (prompt_id, dialect);
create index if not exists prompt_correction_reviews_prompt_idx
on public.prompt_correction_reviews (module_id, prompt_id);
create index if not exists prompt_correction_reviews_created_idx
on public.prompt_correction_reviews (created_at);
create index if not exists research_tasks_status_idx on public.research_tasks (status);
create index if not exists research_tasks_assigned_idx on public.research_tasks (assigned_to);
create index if not exists research_tasks_recording_idx on public.research_tasks (recording_id);
create unique index if not exists research_tasks_one_open_assignee_recording_uidx
on public.research_tasks (recording_id, assigned_to)
where recording_id is not null and assigned_to is not null and status <> 'done';
create index if not exists contributions_username_created_idx
on public.contributions (username, created_at desc);

create or replace view public.prompt_recording_counts
with (security_invoker = true)
as
select
  module_id,
  sentence_id as prompt_id,
  count(*)::integer as recording_count
from public.recordings
group by module_id, sentence_id;

create or replace view public.participant_recording_counts
with (security_invoker = true)
as
select
  participant_id,
  count(*)::integer as recording_count
from public.recordings
group by participant_id;

revoke all on public.prompt_recording_counts from anon, authenticated;
revoke all on public.participant_recording_counts from anon, authenticated;
grant select on public.prompt_recording_counts to service_role;
grant select on public.participant_recording_counts to service_role;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.apply_research_task_result(
  task_id uuid,
  admin_username text
)
returns setof public.research_tasks
language plpgsql
security definer
set search_path = public
as $$
declare
  task_row public.research_tasks%rowtype;
begin
  select * into task_row
  from public.research_tasks
  where id = task_id
  for update;

  if not found then raise exception 'Research task not found.'; end if;
  if task_row.recording_id is null then raise exception 'Research task is not linked to a recording.'; end if;
  if 'transcript' = any(task_row.requested_outputs) and nullif(trim(task_row.transcript), '') is null then
    raise exception 'A transcript is required before applying this task.';
  end if;
  if 'translation' = any(task_row.requested_outputs) and nullif(trim(task_row.translation), '') is null then
    raise exception 'A translation is required before applying this task.';
  end if;
  if not ('transcript' = any(task_row.requested_outputs)) and not ('translation' = any(task_row.requested_outputs)) then
    raise exception 'This assignment has no transcript or translation to apply.';
  end if;

  update public.recordings
  set
    transcript = case when 'transcript' = any(task_row.requested_outputs) then task_row.transcript else transcript end,
    english_translation = case when 'translation' = any(task_row.requested_outputs) then task_row.translation else english_translation end
  where id = task_row.recording_id;

  if not found then raise exception 'Linked recording not found.'; end if;

  return query
  update public.research_tasks
  set status = 'done',
      completed_at = now(),
      applied_to_recording_at = now(),
      applied_by = admin_username,
      updated_at = now()
  where id = task_row.id
  returning *;
end;
$$;

revoke all on function public.apply_research_task_result(uuid, text) from public, anon, authenticated;
grant execute on function public.apply_research_task_result(uuid, text) to service_role;

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'app_users_set_updated_at'
      and tgrelid = 'public.app_users'::regclass
  ) then
    create trigger app_users_set_updated_at
    before update on public.app_users
    for each row
    execute function public.set_updated_at();
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'push_subscriptions_set_updated_at'
      and tgrelid = 'public.push_subscriptions'::regclass
  ) then
    create trigger push_subscriptions_set_updated_at
    before update on public.push_subscriptions
    for each row
    execute function public.set_updated_at();
  end if;
end;
$$;

insert into storage.buckets (id, name, public)
values
  ('audio-recordings', 'audio-recordings', false),
  ('feedback-audio', 'feedback-audio', false),
  ('prompt-media', 'prompt-media', false)
on conflict (id) do nothing;

update storage.buckets
set public = false
where id = 'prompt-media';

alter table public.app_users enable row level security;
alter table public.recordings enable row level security;
alter table public.feedback enable row level security;
alter table public.validations enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.notification_logs enable row level security;
alter table public.admin_accounts enable row level security;
alter table public.admin_activity_logs enable row level security;
alter table public.prompt_bank enable row level security;
alter table public.prompt_correction_reviews enable row level security;
alter table public.research_tasks enable row level security;
alter table public.contributions enable row level security;

drop policy if exists "anon can insert recordings" on public.recordings;
drop policy if exists "anon can insert feedback" on public.feedback;
drop policy if exists "anon can upload audio recordings" on storage.objects;
drop policy if exists "anon can update audio recordings" on storage.objects;
drop policy if exists "anon can upload feedback audio" on storage.objects;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'push_subscriptions'
      and policyname = 'anon can manage push subscriptions'
  ) then
    create policy "anon can manage push subscriptions"
    on public.push_subscriptions
    for all
    to anon
    using (true)
    with check (true);
  end if;
end;
$$;
